version: '3.8'

services:
  app:
    image: ${APP_NAME}:${APP_ENV:-local}
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_NAME=${APP_NAME}
      - APP_PORT=${APP_PORT}
    networks:
      - internal-net

networks:
  internal-net:
    driver: overlay
