version: '3.8'

services:
  app:
    container_name: ${APP_NAME}-${APP_ENV}
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_NAME=${APP_NAME}
      - APP_PORT=${APP_PORT}
    networks:
      - internal-net

networks:
  internal-net:
    driver: bridge
