version: '3'

dotenv: ['.env']
vars:
  APP_ENV: 
    sh: echo ${APP_ENV:-local}
  COMPOSE_CMD:
    sh: |
      if [ "{{.APP_ENV}}" == "local" ]; then
        echo "docker compose -f docker-compose.yml -f docker/docker-compose.local.yaml"
      else
        echo "docker compose -f docker-compose.yml -f docker/docker-compose.prod.yaml"
      fi

tasks:
  install:
    desc: Initialise l'environnement
    cmds:
      - ./docker/scripts/install.sh {{.APP_ENV}}

  build:
    desc: Build les images docker
    cmds:
      - "{{.COMPOSE_CMD}} build"

  watch:
    desc: Lance le mode développement avec hot-reloading
    cmds:
      - "{{.COMPOSE_CMD}} up --build"

  destroy:
    desc: Nettoie les conteneurs et les volumes orphelins
    cmds:
      - ./docker/scripts/destroy.sh

  clean:
    desc: Nettoie les conteneurs et les volumes orphelins
    cmds:
      - "{{.COMPOSE_CMD}} down --rmi all -v"

  up:
    desc: Lance l'environnement (détaché)
    cmds:
      - "{{.COMPOSE_CMD}} up -d"

  down:
    desc: Arrête l'environnement
    cmds:
      - "{{.COMPOSE_CMD}} down"

  deploy:
    desc: Déploie la stack Docker Swarm
    cmds:
      - task: build
      - docker network inspect traefik-net >/dev/null 2>&1 || docker network create --driver overlay --attachable traefik-net || true
      - "{{.COMPOSE_CMD}} config | docker stack deploy -c - $APP_NAME"

  remove:
    desc: Arrête et supprime la stack Docker Swarm
    cmds:
      - docker stack rm $APP_NAME

  status:
    desc: Vérifie le statut des services Swarm
    cmds:
      - docker stack services $APP_NAME
