version: '3'

dotenv: ['.env']

tasks:
  install:
    desc: Initialise l'environnement
    cmds:
      - ./docker/scripts/install.sh $APP_ENV

  build:
    desc: Build l'image
    cmds:
      - docker compose build

  watch:
    desc: Mode dev interactif
    cmds:
      - docker compose -f docker-compose.yml -f docker/docker-compose.local.yaml up --build

  up:
    desc: Lance l'environnement local
    cmds:
      - docker compose -f docker-compose.yml -f docker/docker-compose.local.yaml up -d

  down:
    desc: Arrête l'environnement local
    cmds:
      - docker compose -f docker-compose.yml -f docker/docker-compose.local.yaml down

  deploy:
    desc: Deploy Swarm Stack
    cmds:
      - docker stack rm $APP_NAME || true
      - docker stack deploy -c docker-compose.yml -c docker/docker-compose.prod.yaml $APP_NAME

  status:
    desc: Statut des services Swarm
    cmds:
      - docker stack services $APP_NAME

  remove:
    desc: Supprime la stack Swarm
    cmds:
      - docker stack rm $APP_NAME

  clean:
    desc: Nettoie tout (images & volumes)
    cmds:
      - docker compose down --rmi all -v
