version: '3'

dotenv: ['.env']

tasks:
  # --- CYCLE DÉVELOPPEMENT (LOCAL) ---
  dev:install:
    desc: Initialisation interactive locale
    cmds:
      - ./docker/scripts/install.sh local

  dev:build:
    desc: Build l'image en local
    cmds:
      - docker compose build

  dev:up:
    desc: Dev avec Hot-Reload (Docker Compose Watch)
    cmds:
      - docker compose -f docker-compose.yml -f docker/docker-compose.local.yaml watch

  dev:down:
    desc: Arrête l'environnement local
    cmds:
      - docker compose -f docker-compose.yml -f docker/docker-compose.local.yaml down

  dev:destroy:
    desc: Nettoyage total (Volumes, .env, node_modules)
    cmds:
      - ./docker/scripts/destroy.sh

  # --- CYCLE PRODUCTION (SERVEURS) ---
  prod:install:
    desc: Initialisation sur le serveur distant (Usage CI)
    cmds:
      - ./docker/scripts/install.sh {{.ENV}}

  prod:deploy:
    desc: Déploiement Swarm Stack
    cmds:
      - ./docker/scripts/deploy.sh

  prod:status:
    desc: Statut des services Swarm
    cmds:
      - docker stack services ${APP_NAME}

  prod:remove:
    desc: Supprime la stack Swarm
    cmds:
      - docker stack rm ${APP_NAME}
