services:
  app:
    networks:
      - traefik_proxy
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.http.routers.${APP_NAME}.rule=Host(`${APP_DOMAIN}`)"
        - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"

networks:
  traefik_proxy:
    external: true
