name: Dev Deployment

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create destination directory
        run: mkdir -p ~/dev/${{ secrets.SSH_PATH }}

      - name: Sync files
        run: |
          rsync -avz --delete \
            --exclude '.git' \
            --exclude '.github' \
            ./ ~/dev/${{ secrets.SSH_PATH }}

      - name: Initialize Environment
        run: |
          cd ~/dev/${{ secrets.SSH_PATH }}
          task install
        env:
          APP_ENV: dev
